- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.75.0 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
  hooks:
    - id: terraform_tflint
    - id: terraform_fmt
    - id: terraform_tfsec
    - id: terraform_docs
    - id: terraform_validate
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: check-merge-conflict
    - id: check-yaml
    - id: check-added-large-files
    - id: trailing-whitespace
